//! `[file_kinds.<repo>]` — per-repo corrections to how a path is classified.
//!
//! [`classify_path`] knows the common conventions (lockfiles, `dist/`, `*.test.ts`)
//! but not a project's own codegen directory or e2e folder. A repo names those
//! here, keyed the same way as `[importance.<repo>]` and for the same reason:
//! there is no repo-local config (ADR 0005).
//!
//! ```toml
//! [file_kinds.my-service]
//! "src/api/schema/**" = "generated"
//! "e2e/**" = "test"
//! "scripts/**" = "production"
//! ```

use super::path_rules;
use crate::git::{classify_path, FileKind};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct FileKindsConfig {
    #[serde(flatten)]
    pub items: BTreeMap<String, FileKindRepoConfig>,
}

/// One repo's overrides: keys are paths, globs or file types, values are kinds.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(default)]
pub struct FileKindRepoConfig {
    #[serde(flatten)]
    pub rules: BTreeMap<String, String>,
}

impl FileKindsConfig {
    /// The overrides declared for `repo`, if there are any.
    pub fn repo(&self, repo: &str) -> Option<&FileKindRepoConfig> {
        self.items.get(repo)
    }
}

impl FileKindRepoConfig {
    /// Kind of a repo-relative path: the override that claims it, else the
    /// built-in conventions. An override whose kind does not read is ignored
    /// rather than failing the load, same as an unreadable importance tier.
    pub fn classify(&self, path: &str) -> FileKind {
        path_rules::matching_rule(&self.rules, path, FileKind::parse)
            .map_or_else(|| classify_path(path), |(_, kind)| kind)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rules(pairs: &[(&str, &str)]) -> FileKindRepoConfig {
        FileKindRepoConfig {
            rules: pairs
                .iter()
                .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
                .collect(),
        }
    }

    #[test]
    fn no_overrides_falls_back_to_conventions() {
        let table = FileKindRepoConfig::default();
        assert_eq!(table.classify("src/lib.rs"), FileKind::Production);
        assert_eq!(table.classify("Cargo.lock"), FileKind::Generated);
    }

    #[test]
    fn override_reclassifies_project_paths() {
        let table = rules(&[("src/api/schema/**", "generated"), ("e2e/**", "test")]);
        assert_eq!(table.classify("src/api/schema/types.ts"), FileKind::Generated);
        assert_eq!(table.classify("e2e/login.ts"), FileKind::Test);
        assert_eq!(table.classify("src/api/client.ts"), FileKind::Production);
    }

    #[test]
    fn override_can_promote_a_convention_back_to_production() {
        // `dist/` is generated by convention; a repo that commits a hand-written
        // `dist/` says so.
        let table = rules(&[("packages/cli/dist/**", "production")]);
        assert_eq!(table.classify("packages/cli/dist/run.js"), FileKind::Production);
        assert_eq!(table.classify("packages/web/dist/run.js"), FileKind::Generated);
    }

    #[test]
    fn file_type_rule_matches_basename() {
        let table = rules(&[("*.gen.ts", "generated")]);
        assert_eq!(table.classify("deep/dir/a.gen.ts"), FileKind::Generated);
    }

    #[test]
    fn unreadable_kind_falls_through_to_conventions() {
        let table = rules(&[("src/**", "genrated")]);
        assert_eq!(table.classify("src/lib.rs"), FileKind::Production);
    }

    #[test]
    fn parses_from_toml_under_repo_key() {
        let config: FileKindsConfig =
            toml::from_str("[my-service]\n\"e2e/**\" = \"test\"\n").unwrap();
        let table = config.repo("my-service").unwrap();
        assert_eq!(table.classify("e2e/a.ts"), FileKind::Test);
    }

    /// The desktop rewrites the whole config on every settings save, and the
    /// overrides are hand-written, so a save must carry them through intact.
    #[test]
    fn overrides_survive_a_config_save_round_trip() {
        let text = "[file_kinds.my-service]\n\"src/api/schema/**\" = \"generated\"\n\"*.gen.ts\" = \"generated\"\n\n[display]\ntheme = \"slate\"\n";
        let config: crate::config::ErConfig = toml::from_str(text).unwrap();
        // Same serializer `save_config` uses.
        let saved = toml::to_string_pretty(&config).unwrap();
        let reloaded: crate::config::ErConfig = toml::from_str(&saved).unwrap();
        let table = reloaded.file_kinds.repo("my-service").unwrap();
        assert_eq!(table, config.file_kinds.repo("my-service").unwrap());
        assert_eq!(table.classify("src/api/schema/a.ts"), FileKind::Generated);
        assert_eq!(table.classify("lib/x.gen.ts"), FileKind::Generated);
    }
}
