/** Run against Storybook with DOCUMENT_STORYBOOK_URL=http://127.0.0.1:6017 bun scripts/check-document-previews.ts. */
import assert from "node:assert/strict";
import { chromium } from "playwright";
const base = process.env.DOCUMENT_STORYBOOK_URL ?? "http://127.0.0.1:6006";
const browser = await chromium.launch();
try {
  for (const story of ["unified", "split", "guide"]) {
    const page = await browser.newPage({ viewport: { width: 1100, height: 800 } });
    let releaseImage: (() => void) | undefined;
    const imageReady = new Promise<void>((resolve) => { releaseImage = resolve; });
    await page.route("https://images.unsplash.com/**", async (route) => {
      await imageReady;
      await route.fulfill({ contentType: "image/svg+xml", body: '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><rect width="800" height="400" fill="#888"/></svg>' });
    });
    await page.goto(`${base}/iframe.html?id=diff-document-previews--${story}&viewMode=story`);
    const preview = page.locator('[data-document-preview="docs/README.MD"]');
    await preview.locator("h1").waitFor();
    const band = page.locator(".hscroll");
    await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))));
    const beforeImage = await band.evaluate((el) => el.getBoundingClientRect().height);
    releaseImage?.();
    await preview.locator("img").evaluate((image) => new Promise<void>((resolve) => {
      if ((image as HTMLImageElement).complete) resolve(); else image.addEventListener("load", () => resolve(), { once: true });
    }));
    await page.waitForFunction((before) => (document.querySelector(".hscroll")?.getBoundingClientRect().height ?? 0) > before + 150, beforeImage);
    assert.equal(await preview.locator("table").count(), 1);
    assert.equal(await preview.locator('a[href="./README.md"]').count(), 0);
    const width = await preview.evaluate((el) => el.getBoundingClientRect().width);
    const bandWidth = await band.evaluate((el) => el.getBoundingClientRect().width);
    assert(Math.abs(width - bandWidth) < 2, `${story} preview spans the diff column`);
    await page.locator(".vscroll").evaluate((el) => { el.scrollTop = 700; });
    await page.locator(".vscroll > .sticky").getByRole("button", { name: "Raw", exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('[data-document-preview="docs/README.MD"]'));
    assert((await page.locator(".vscroll").evaluate((el) => el.scrollTop)) < 80, "sticky switch anchors at the clicked file");
    const header = page.locator(".file-header-viewport-row").filter({ hasText: "README.MD" });
    await header.getByRole("button", { name: "Preview", exact: true }).click();
    await preview.locator("h1").waitFor();
    await header.getByRole("button", { name: "Collapse file diff" }).click();
    await page.waitForFunction(() => !document.querySelector('[data-document-preview="docs/README.MD"]'));
    await header.getByRole("button", { name: "Expand file diff" }).click();
    await preview.locator("h1").waitFor();
    await page.getByRole("button", { name: "Jump to document hunk" }).click();
    await page.waitForFunction(() => !document.querySelector('[data-document-preview="docs/README.MD"]'));
    // Existing thread replies, finding replies and AI context survive card unmounts.
    const thread = page.locator("#document-thread");
    await thread.getByRole("button", { name: "Reply", exact: true }).click();
    const reply = thread.getByPlaceholder("Reply… (⌘+Enter to send)");
    await reply.fill("Existing thread reply draft");
    const findingReply = page.locator("#finding-document-finding").getByPlaceholder("Reply to this finding…");
    await findingReply.fill("Existing finding reply draft");
    await page.locator(".vscroll").evaluate((el) => { el.scrollTop = 0; });
    await header.getByRole("button", { name: "Preview", exact: true }).click();
    await preview.locator("h1").waitFor();
    assert.equal(await thread.count(), 0);
    await header.getByRole("button", { name: "Raw", exact: true }).click();
    await reply.waitFor();
    assert.equal(await reply.inputValue(), "Existing thread reply draft");
    assert.equal(await findingReply.inputValue(), "Existing finding reply draft");
    await thread.getByRole("button", { name: "Ask AI…", exact: true }).click();
    const aiContext = thread.getByPlaceholder("Add context for the AI… (leave empty for default · ⌘+Enter to send)");
    await aiContext.fill("Unsent AI context draft");
    await page.locator(".vscroll").evaluate((el) => { el.scrollTop = 0; });
    await header.getByRole("button", { name: "Preview", exact: true }).click();
    await preview.locator("h1").waitFor();
    await header.getByRole("button", { name: "Raw", exact: true }).click();
    await aiContext.waitFor();
    assert.equal(await aiContext.inputValue(), "Unsent AI context draft");
    await aiContext.press("Escape");
    await page.locator(".vscroll").evaluate((el) => { el.scrollTop = 0; });
    await header.getByRole("button", { name: "Preview", exact: true }).click();
    await preview.locator("h1").waitFor();
    await page.getByRole("button", { name: "Search document diff" }).click();
    const input = page.getByPlaceholder("Search diff");
    await input.waitFor();
    await page.waitForFunction(() => document.querySelector("[data-diff-search-bar]")?.textContent?.includes("1 / 4"));
    assert.match(await page.locator("[data-diff-search-bar]").innerText(), /1 \/ 4/);
    await input.press("Enter");
    await page.waitForFunction(() => !document.querySelector('[data-document-preview="docs/README.MD"]'));
    await input.press("Escape");
    await page.getByRole("button", { name: "Open document draft" }).click();
    await header.getByRole("button", { name: "Preview", exact: true }).click();
    await preview.locator("h1").waitFor();
    assert.equal(await page.locator("[data-story-draft]").innerText(), "Keep this draft");
    await page.getByRole("button", { name: "Clear draft" }).click();
    await page.setViewportSize({ width: 480, height: 800 });
    await page.locator(".vscroll").evaluate((el) => { el.scrollTop = 0; });
    const rawButton = header.getByRole("button", { name: "Raw", exact: true });
    const bounds = await rawButton.boundingBox();
    assert(bounds && bounds.x >= 0 && bounds.x + bounds.width <= 480, "narrow header fits the viewport");
    await page.getByRole("button", { name: "Jump to notes", exact: true }).click();
    const text = page.locator('[data-document-preview="notes.text"] pre');
    await text.waitFor();
    assert.match(await text.innerText(), /\n {4}Indented text\n\tTabbed text/);
    assert.equal(await text.evaluate((el) => getComputedStyle(el).whiteSpace), "pre-wrap");
    await page.getByRole("button", { name: "Jump to empty document" }).click();
    await page.locator('[data-document-preview="empty.md"]').getByText("Empty file").waitFor();
    await page.getByRole("button", { name: "Jump to unavailable document" }).click();
    const unavailableHeader = page.locator(".file-header-viewport-row").filter({ hasText: "unavailable.md" });
    await unavailableHeader.getByRole("button", { name: "Preview", exact: true }).click();
    const unavailable = page.locator('[data-document-preview="unavailable.md"]');
    await unavailable.getByText("Preview unavailable", { exact: true }).waitFor();
    await unavailable.getByRole("button", { name: "Retry" }).click();
    await unavailable.getByText("Preview unavailable", { exact: true }).waitFor();
    await unavailableHeader.getByRole("button", { name: "Raw", exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('[data-document-preview="unavailable.md"]'));
    console.log(`${story} document preview browser checks passed`);
    await page.close();
  }
  const many = await browser.newPage({ viewport: { width: 1100, height: 4000 } });
  await many.goto(`${base}/iframe.html?id=diff-document-previews--many-short-documents&viewMode=story`);
  await many.waitForFunction(() => document.querySelectorAll("[data-document-preview] pre").length === 24);
  assert.equal(await many.getByText("Loading preview…", { exact: true }).count(), 0);
  await many.locator(".vscroll").evaluate((el) => { el.scrollTop = 30; });
  await many.waitForFunction(() => document.querySelectorAll("[data-document-preview] pre").length === 24);
  assert.equal(await many.locator("[data-document-preview] pre").count(), 24);
  await many.close();
  console.log("24 mounted document previews survive bounded cache eviction");
} finally { await browser.close(); }
